### PR TITLE
Fix issue with printf and passwords with `%`

### PR DESCRIPTION
**Pull request by alexpdp7**
```
$ cat <<EOF >foo
>   apiVersion: v1
>   data:
>     password: "$(printf ${GITLAB_PASSWORD} | base64 -w0)"
>     username: "$(printf ${GITLAB_USER} | base64 -w0)"
>   kind: Secret
>   metadata:
>     annotations:
>       tekton.dev/git-0: https://${GIT_SERVER}
>     labels:
>       credential.sync.jenkins.openshift.io: "true"
>     name: git-auth
> EOF
```

Produces:

```
sh: printf: `S': invalid format character                        
```

then...

```
$ cat foo
  apiVersion: v1
  data:
    password: "....U1A6d2g/a0w="
    username: "YWxleGNvcmNvbGVz"
  kind: Secret
  metadata:
    annotations:
      tekton.dev/git-0: https://gitlab-ce.apps.tl500-1.ls-eu.ole.redhat.com/
    labels:
      credential.sync.jenkins.openshift.io: "true"
    name: git-auth
$ echo ...U1A6d2g/a0w= | base64 -d ; echo
....SP:wh?kL
$ echo $GITLAB_PASSWORD
...SP:wh?kL%S
```

Using `echo -n`:

```
$ cat <<EOF >foo
>   apiVersion: v1
>   data:
>     password: "$(echo -n ${GITLAB_PASSWORD} | base64 -w0)"
>     username: "$(echo -n ${GITLAB_USER} | base64 -w0)"
>   kind: Secret
>   metadata:
>     annotations:
>       tekton.dev/git-0: https://${GIT_SERVER}
>     labels:
>       credential.sync.jenkins.openshift.io: "true"
>     name: git-auth
> EOF
$ cat foo
  apiVersion: v1
  data:
    password: "...6d2g/a0wlUw=="
    username: "YWxleGNvcmNvbGVz"
  kind: Secret
  metadata:
    annotations:
      tekton.dev/git-0: https://gitlab-ce.apps.tl500-1.ls-eu.ole.redhat.com/
    labels:
      credential.sync.jenkins.openshift.io: "true"
    name: git-auth
$ echo WDA6dE84U1A6d2g/a0wlUw== | base64 -d ; echo
....SP:wh?kL%S
$ echo $GITLAB_PASSWORD
...SP:wh?kL%S
```

### CODE REVIEW

**Comment by alexpdp7** [comment]
I think the PR is right, but the next steps in the tutorial are failing, so maybe it's not correct...

**Comment by eformat** [comment]
@alexpdp7  - what shell and environment are you using here ? these work fine from previous runs in zsh and bash on CRW ?

**Comment by eformat** [comment]
OK, if your password has % in it .. then only 2 sane approaches .. use %% to escape 
or we change to echo -n

**Comment by alexpdp7** [comment]
As discussed, this only happens if the password contains `%`.

**Comment by eformat** [comment]
i will change it to echo -n .. no big deal ! and will check for other occurrances ... thats should fix it

**Comment by eformat** [comment]
fixed with - https://github.com/rht-labs/tech-exercise/commit/47e4373005b49d859ee969220ef37d34739d343d

**Pull request closed without merging**
