### PR TITLE
✨ Set up a new group (hope) in the team

### PR DESCRIPTION
**Pull request by rmarting**
This PR is proposed as the implementation of the #246 exercise template.

Open to get feedback, comments, and enhacements from other facilitators.

### CODE REVIEW

**Comment by ckavili** [comment]
that looks good @rmarting! 🤸‍♀️ my only comment would be changing the file name [1-tooling-installation.md](https://github.com/rh-open-innovation-labs/tech-exercise/blob/a-new-hope-exercise/docs/98-a-new-group/1-tooling-installation.md) into something like `1-create-new-group.md` and update the sidebar accordingly 🙈

**Comment by rmarting** [comment]
Sorry @ckavili for my long delay!!! Just applied your comments. I hope this contribution could help on your ongoing enablement.
image

**Comment by eformat** [comment]
hi @rmarting - what do you think about incorporating these instructions in 1-the-manual-menace ? it seems odd to have it under its own section - 98-a-new-group ?

**Comment by ckavili** [comment]
hmm then maybe under 2-attack-of-the-pipelines right before or after we introduce Jenkins and Tekton where they can go into pairing mode?

**Comment by eformat** [comment]
> hmm then maybe under 2-attack-of-the-pipelines right before or after we introduce Jenkins and Tekton where they can go into pairing mode?
👍

**Comment by rmarting** [comment]
@ckavili @eformat What do you think? Does it make sense now? I have to admit that now the history is better.

**Comment by ckavili** [comment]
yup it looks good to me! thanks @rmarting 🚀

**Pull request merged**
