### PR TITLE
🧐 [Experiment][WIP] Moving Outcomes and Big Picture before tech instructions

### PR DESCRIPTION
**Pull request by rmarting**
:rotating_light: This is an experiment and is open to discussion, and revision before merging it.

After a set of runs, we found that in many cases the attendees don't follow up on the big picture at the beginning of the activity, as many of the concepts, or tools are described later.

@earvonen proposed a new idea to move the outcomes and big picture after the practices of the technical exercise and before the exercise instructions. It was very well from there and we applied it in the rest of the technical exercises.

The attendees gave us good feedback about this new approach and we could explain better the components and their functions in the big picture.

We are glad to get other opinions, comments, and ideas about this experiment.

### CODE REVIEW

**Comment by earvonen** [comment]
@rmarting summarized my point quite well, but just to elaborate:
Let's say I present exercise 5 as it is before this pull request. 

We go to the Big Picture very early and I start whipping out cards with HPA, blue and green tags and A and B variants. The audience is completely unprepared for these. I'm explaining what these concepts mean as I go, and it's stressful to me as a presenter because I have to focus on two things at once.

The audience gets the feeling they're being thrown into the deep end and I expose myself needlessly to questions that will be answered in the slides. If I answer briefly, I risk getting into rabbit holes and waste time. If I answer in full, I'm doing it without the visualisation aides in the slides.

After the Big Picture is updated, I send the attendees back to their seats. The next thing they see is Target Outcomes for the exercise. I find this to be way too early, because I'm now about to give them comprehensive explanations of what A/B, Blue/Green, Canary, Autoscaling and Feature Toggling means. 

With the proposed changes the slides will save a lot of time because those things won't have to be repeated in the Big Picture stage. We are only showing _where_ each practice will be deployed instead of pouring all the information at once.

I think the Target Outcomes should be either before or after the Big Picture update.

For Exercise 5 I think the better place for Target Outcomes is **before** Big Picture. This is because the attendees will know the drill by now: Choose Your Own Adventure. In fact, we can skip the following slides and attendees can start off right away. 

Exercise 3 is the first time the team is encountering Choose Your Own Adventure. Here it might be prudent to move Target Outcomes further, possibly all the way to the end of the slides.

**Comment by springdo** [comment]
Yeah sounds good to me! Happy to merge this PR 🪂

**Comment by springdo** [comment]
Just need the WIP removed

**Comment by rmarting** [comment]
Removed [WIP] description ... as it is already merged into the master!

Thanks @springdo!

**Pull request merged**
