### PR TITLE
🦜 OCP 4.11 🦜

### PR DESCRIPTION
**Pull request by eformat**
Updates to tech exercise docs to support 4.11

These changes will work on 4.9/4.10 existing runs as well.

The main breaking change is 4.11 and DevSpaces (removal of CRW) .. that has v2 devfile format

### CODE REVIEW

**Comment by eformat** [comment]
Related: https://github.com/rht-labs/enablement-framework/pull/147

**Comment by jfilipcz** [comment]
Hey @eformat, have you done any testing on 4.9 or 4.10? We still got some movement on those, and cannot upgrade LodeStar to support 4.11 atmo

**Comment by eformat** [comment]
yo @jfilipcz  .. yes .. also note ocp lifecycle dates - https://access.redhat.com/support/policy/updates/openshift

4.8 - yes, we have been running tl500 in this
4.9 - no, not for a long time - its in maintenance support only now
4.10 - yes, the RHPDS deployment of main - is on this version, been working well - full support ends November 10, 2022
4.11 - yes, the nightly tests run on this, i have run through all of tl500 using this version and DevSpaces.

None of these changes are impacting on current versions. They are additional for 4.11 - i.e DevSpaces.

**Review by jfilipcz — APPROVED** [review]
LGTM!

**Pull request merged**
