### PR TITLE
Add change uname/pass tip to step8 in the basics

### LINKED ISSUE #130: 🐛 [bug] Basics step 8 change uname pword
### 📝 Description
Step 8 in the basics says to "check if you can connect to openshift" and has a copy and paste snippet.  It does not point out the need to CHANGE the username and password before entering the command in the IDE.

### 🚶 Steps to reproduce
... if applicable

### 🧙‍♀️ Suggested solution
Add "Note: Change the <USERNAME> and <PASSWORD> to match your team's login details before hitting enter."
or something to that effect.

### PR DESCRIPTION
**Pull request by kattekrab**
Resolves #130

### CODE REVIEW

**Review by eformat — CHANGES_REQUESTED** [review]
please use this as a TIP

```html
<p class="tip">
  ⛷️ <b>TIP</b> ⛷️ - Don't include the `https://` in <i>any</i> of the variable boxes at the top of the page.
</p>
```

**Comment by kattekrab** [comment]
Aaah sweet.  Thanks @eformat - done.

**Comment by kattekrab** [comment]
oops looks like I've messed up the code snippet - I'll try to fix now.

**Comment by kattekrab** [comment]
yup, that seemed to sort it.

**Pull request merged**
