### PR TITLE
Updated Big Pictures with latest status of the Technical Exercises

### PR DESCRIPTION
**Pull request by rmarting**
This PR includes a set of commits with a sequence updated of each Big Picture aligned with the activities, goals and task in each technical exercise. 

Basically the sequence of commits includes the next summary of changes:

**The Manual Manace**
- Reordered Dev tools (grouping by framework+tool)
- Removed jenkins-agents

**Attack of the Pipelines**
- Removed testing and promoting stages
- Updated bake and deploy steps

**Revenge the Automated Testing**
- Aligned with previous Big Pictures, following the same structre

**Return of the Monitoring**
- Added logging namespace and tools

**The Deployments Strike Back**
- Added HPA tool
- Added B/G Deployments for Pet-Battle-UI for test environment
- Added A/B Deployments for Pet-Battle-UI in stage environment

This PR could help to fix the following issues:
- #167 
- #168 
- #169

### CODE REVIEW

**Comment by springdo** [comment]
Cheers for this Roman!! If i can make one suggestion, as we noticed it in London and I forgot to update it, but can you put `Grafana` into the `ci-cd` namespace? @ckavili will be able to correct me if Im wrong but I think we deploy it per teams ci-cd ns

**Comment by ckavili** [comment]
yup yup Grafana is installed in each ci-cd namespace by teams :)

**Comment by rmarting** [comment]
Just uploaded the new versions of the Big Picture moving Grafana into ci-cd namespace for the final exercises. Also the source diagrams in the Miro Board are already updated.

WDTY?

**Comment by springdo** [comment]
Yeoowwwww nailed it and smashed it in

**Pull request merged**
