### PR TITLE
🙈 Hidding System Test activities

### PR DESCRIPTION
**Pull request by rmarting**
This exercise is not defined yet. Hide to avoid confusion.

Many students ask about this exercise/activity as the content is empty and no clear actions to execute. It could be better not to show it until there is a clear activity to do.

### CODE REVIEW

**Comment by rmarting** [comment]
@ckavili @springdo @eformat Comments? Every time a deliver the TL500 got the same question: "_What should we do in System Test?_, _what is the goal of this step?_

Until we don't provide an example/activity, we could skip it. WDYT?

**Comment by eformat** [comment]
The work is never done. This is a good way to explain that even TL500 is not finished !
and we get to use @springdo name in vein .. since HE PROMISED to do this section .. for over a year now ...

image

I Vote we keep it IN ... until the work is done ...

**Comment by eformat** [comment]
https://github.com/rht-labs/tech-exercise/issues/7

**Comment by ckavili** [comment]
Ahaha I like how Mike put an evidence there to prove over a year🙈🙈 like Mike said, I enjoy joking around with @springdo but it's okay for me to comment those out for now as long as we don't forget to update the picture and everything :D

**Comment by ckavili** [comment]
(sorry hit close by mistake 🙈)

**Comment by springdo** [comment]
**I WILL DO THIS!!!**

 You guys just need to keep faith.... How about I try do it before the NA runs and if it's not done by then, then you can comment it out 🙏

**Comment by ckavili** [comment]
That sound good! (not sure if time pressure ever worked on you though :p) 
C05FCBFB-3866-4EAB-9D03-5C3A54EF6730

**Comment by rmarting** [comment]
Team! I don't want to pressure anyone ... not now in Summer :smile:. I was only thinking about the students and facilitating their technical exercises. I am comfortable with the @eformat message about _We are working on it, as we are an agile team_ so as you decide, accept or reject it.

bitmoji

**Comment by eformat** [comment]
no pressure @springdo 

image

**Comment by eformat** [comment]
hy @ckavili i wonder if @springdo will bring us a christmas present on #192 ?!? 

image

**Comment by springdo** [comment]
Ahhhhh @eformat I actually started this a few weeks ago but got side lined with other stuff.... I know the exercise works at least cuz I did a demo of it (by request) at the last run of the course I'm Dublin 😁

Perhaps if yous are nice Santa Spring will bring you a lovely sack of tests

**Comment by ckavili** [comment]
no pressure..right @eformat? 😌
image

**Comment by eformat** [comment]
@springdo - pressure ? what pressure @ckavili ?

image

**Comment by springdo** [comment]
image

**Comment by ckavili** [comment]
image

**Comment by ckavili** [comment]
is this that time of the year? @eformat 🤔 
image

**Comment by eformat** [comment]
image

**Comment by springdo** [comment]
image

**Comment by springdo** [comment]
y'all ready for this ....

**Comment by ckavili** [comment]
image

**Comment by springdo** [comment]
erm --- toooo late https://github.com/rht-labs/tech-exercise/pull/275 
image

**Comment by springdo** [comment]
this will be waiting for the PR to be accepted now ....
image

**Comment by rmarting** [comment]
Great job @springdo !!! Now I can close this PR as you did the job and now the Pet Battle teams can enjoy with more exercises ... 🪅👏🪅👏🪅

**Pull request closed without merging**
